/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';

/**
 * @category Instructions
 * @category InitUserProfile
 * @category generated
 */
export type InitUserProfileInstructionArgs = {
  twitterHandle: string;
};
/**
 * @category Instructions
 * @category InitUserProfile
 * @category generated
 */
export const initUserProfileStruct = new beet.FixableBeetArgsStruct<
  InitUserProfileInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['twitterHandle', beet.utf8String],
  ],
  'InitUserProfileInstructionArgs'
);
/**
 * Accounts required by the _initUserProfile_ instruction
 *
 * @property [_writable_] userProfile
 * @property [_writable_, **signer**] authority
 * @category Instructions
 * @category InitUserProfile
 * @category generated
 */
export type InitUserProfileInstructionAccounts = {
  userProfile: web3.PublicKey;
  authority: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const initUserProfileInstructionDiscriminator = [
  148, 35, 126, 247, 28, 169, 135, 175,
];

/**
 * Creates a _InitUserProfile_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitUserProfile
 * @category generated
 */
export function createInitUserProfileInstruction(
  accounts: InitUserProfileInstructionAccounts,
  args: InitUserProfileInstructionArgs,
  programId = new web3.PublicKey('F76mQ6wUu1sq4zkEuACCAWLD9E6EJd66BfokCzWDwHWo')
) {
  const [data] = initUserProfileStruct.serialize({
    instructionDiscriminator: initUserProfileInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.userProfile,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
